function AddCatchLog(path){
    var err_name = path.node.param.name
    path.node.body.body.unshift({
        "type": "ExpressionStatement",
        "expression": {
            "type": "CallExpression",
            "callee": {
                "type": "MemberExpression",
                "computed": false,
                "object": {
                    "type": "Identifier",
                    "name": "console"
                },
                "property": {
                    "type": "Identifier",
                    "name": "log"
                }
            },
            "arguments": [
                {
                    "type": "Identifier",
                    "name": err_name
                }
            ]
        }
    })
}

function Replacer(path){
    var s = [
        "?",
        "prototype",
        "call",
        "setAttribute",
        "type",
        "string",
        "href",
        "slice",
        "getAttribute",
        "=",
        "appendChild",
        "#",
        "readyState",
        "hasOwnProperty",
        "replace",
        "location",
        "getElementById",
        "apply",
        "action",
        "pathname",
        "{",
        "(",
        "event",
        ";",
        "status",
        "indexOf",
        "XMLHttpRequest",
        "removeEventListener",
        ".",
        "undefined",
        "eval",
        "&",
        "charCodeAt",
        "ActiveXObject",
        "getTime",
        "+=",
        "src",
        "parentNode",
        "input",
        "nodeType",
        "div",
        "object",
        ",",
        "tagName",
        "onclick",
        "form",
        "toString",
        "floor",
        "innerHTML",
        "clientData",
        ">",
        "search",
        "localStorage",
        "protocol",
        "responseText",
        "]",
        "style",
        "EkcP",
        "onreadystatechange",
        "name",
        "test",
        "port",
        "hidden",
        "keyCode",
        "}",
        "method",
        "open",
        "onload",
        "number",
        "body",
        "splice",
        "ytg|omgzux",
        "target",
        "responseType",
        "button",
        "submit",
        "click",
        "onsubmit",
        "EventTarget",
        "a",
        "\"",
        "concat",
        "/",
        "-",
        "userAgent",
        "createElement",
        "removeChild",
        "https:",
        "addEventListener",
        "function",
        "value",
        "load",
        ":",
        "setInterval",
        "showModalDialog",
        "onerror",
        "script",
        "g",
        ")",
        "cookie",
        "originalTarget",
        "defaultPrevented",
        "Open",
        "\\{(.+?)\\}",
        "throws",
        "rangeMin",
        "_blank",
        "response",
        "lastIndexOf",
        "replaceChild",
        "mozIndexedDB",
        "%",
        "Unexpected character: ",
        "HTMLAnchorElement",
        "Msxml2.ServerXMLHTTP.4.0",
        "}6gcn4nc{gtF6gcn4nc{gt@voA Yevkxg< [qpvtqn @KJEdkvA",
        "/T7AyTrxoWxGd",
        "return a[b](",
        "n__jvsuezive_vir}hrgv",
        "cookie disabled",
        "battery",
        "except",
        "TK_STRING",
        "getUniformLocation",
        "dblclick",
        "MEDIUM_INT",
        "{zmwmfmpmx}glerki",
        "text",
        "behavior",
        "resolvedOptions",
        "oNvg~sfya~NO mhqd q / ~ui 6qfuNO- turgwwud- dufgd~ ~ui 6qfuNO S q 0 WVV-oNOO",
        "yield",
        "Only one variable declaration allowed in for..in loop",
        "getSources",
        "data:",
        "level",
        "itemSize",
        "'",
        "message",
        "|",
        "]><i></i><![endif]-->",
        "pushNotification",
        "Number",
        "clientInformation",
        "enabledPlugin",
        "kyn}j<kbbiwhyyd",
        "Send",
        "$_vJTp",
        "Z8XHj",
        "credentials",
        "responseURL",
        "offsetTop",
        "onloadend",
        "documentElement",
        "$_fh0",
        "func",
        "const",
        "https://",
        "fillText",
        "OBJECT",
        "setClientData",
        "candidate",
        "@debugger",
        "TK_NAME",
        "18px 'Arial'",
        "__#classType",
        "mGwAct:{~~:cfaHcc~TGcyciAgw",
        "http",
        "indexedDB",
        "shaderSource",
        "drawArrays",
        "getResponseHeader",
        "[",
        "this",
        "overrideMimeType",
        "charging",
        "JavaException",
        "unshift",
        "MSPointerEvent",
        "Function",
        "clientX",
        "XMLHttpRequestEventTarget",
        "synchronized",
        "vertexAttribPointer",
        "GetAllResponseHeaders",
        " height=6 width=1 type=application/x-shockwave-flash src=",
        "$_YWTU",
        "then",
        "preload",
        "match",
        "false",
        "fontFamily",
        "Request",
        "ontimeout",
        "clearInterval",
        "jbscheme://queue_has_message",
        "Object.InjectedScript.evaluate",
        "refresh",
        "MediaStreamTrack",
        "cY#rDABASAnA0ATA61Xs<s>VwR;FnF$F%F MqM8MIMGQqQhQWQHQAQpQMQbQvQ^Q&Q*wvw7wzwnwuwZ8c8k8o8s8V8Y8.IqIrIcIlImIDIMIQI_I4IZGQG8GIGGGvGLG-G7GzGCG6G@G$fxf^f&f*f(f)f}PmOjO-O6OgO|O 9g9_949@9$9%9&9*9(9)9:9;2m2D222bbUbfb7bzb<b>v4v*LtLhL)jUjfjP-2-b-@-%-&-=-<7u7_74zfXzXXXuX_X4XZXeX5XdX~X BqBrBcB-B7BzBXBBBCBgB&6~$o$E$v$L%1%P%O%9%y&{(I(G(L(N(j+i+H=l=m=@=$=%=>=.=?=/=:<s>d.K.U.w.8.9.2.b?x?t?h?j?B?a?S?n?u:h:W:J:i{D{1{U#!#rkArkprk$rk%rk rmurn&rn*mf!mf.mf?mOAmOpmbUmbMmbGmbgmbymb_mb4mbZmvZmvemLvmjkmjlmj0m-hm-Wm-Jm-1m-sm-Vm7Xm7Bm7am7Sm7nm7um70m7Tm7@m7=m7<mzfmz]mXlmXmmXhmXWmXimS2mSbmSvmSLmSNmSjmS-mS7mSXmSBEtQEsAEspEKp",
        "Element",
        "i",
        "mouseout",
        "|zhegulyhuFhydoxdwh",
        "(this);",
        "alpha",
        "head",
        "preventDefault",
        "fetch",
        "getSupportedExtensions",
        "c",
        "document",
        "responseBody",
        "nodeName",
        "RegExp",
        "keydown",
        "MEDIUM_FLOAT",
        "checked",
        "MicroMessenger",
        "round",
        "applicationCache",
        "Microsoft.XMLHTTP.1.0",
        "while",
        "b$gnnj$+$$knffdq+$$kro+$$krqa+$gcw$+$qd~cxBncd@kqd~cxDwdbtsdcHmSghrEq~ld+$rcw$+$thd$",
        "console",
        "yjxo|kxIk|gr{gzk",
        "case",
        "SetRequestHeader",
        "gamma",
        "~",
        ", expected ",
        "numItems",
        "implements",
        "http:",
        "[native code]",
        "DeviceOrientationEvent",
        "float",
        "position",
        "hostname",
        "$b_onBridgeReady",
        "canvas",
        "timeStamp",
        "PerformanceObserver",
        "mousedown",
        "m",
        "loaded",
        "msCrypto",
        "width",
        "class",
        "Math",
        "compileShader",
        "super",
        "link",
        "utf-8",
        "getClientDataInCookie",
        "webkitConnection",
        "Keyboard",
        " srflx ",
        "}9[;gd)zvDweygd",
        "createDataChannel",
        "onsuccess",
        "getContext",
        "default",
        "javascript: void(0);",
        "unload",
        "history",
        "P",
        "lvtv{x_",
        "Infinity",
        "switch",
        "ARSession,AudioTrackList,BeforeInstallPromptEvent.prototype.KEYUP,BlobDownloadCallback,CDATASection.prototype.remove,CSSCharsetRule,CSSPrimitiveValue.CSS_VH,CanvasRenderingContext2D.prototype.webkitGetImageDataHD,ClickData,CloseEvent.prototype.initCloseEvent,Components.interfaces.ICometMarksExtension,Function.prototype.bind,GetPerfTests,HTMLDocument.prototype.createTouchList,HTMLFormElement.prototype.requestAutocomplete,HTMLFrameSetElement.prototype.hasPointerCapture,HTMLFrameSetElement.prototype.webkitRequestFullScreen,Intl,MTT_WKSetTextSizeIndex,MediaController,MediaEncryptedEvent,Notification,Object.prototype.__defineSetter__,Object.seal,Object.setPrototypeOf,OffscreenCanvasRenderingContext2D,Path2D.prototype.addPath,PerformancePaintTiming,ReaderModeArticlePage,SVGGraphicsElement.prototype.mozRequestPointerLock,SVGPatternElement.SVG_UNIT_TYPE_OBJECTBOUNDINGBOX,ScreenOrientation,SogouLoginUtils,SourceBuffer,SourceBuffer.prototype.changeType,SpeechSynthesisUtterance,TextTrackList.prototype.getTrackById,UCWebExt,WebKitFlags,_WXJS,__$_qihoo360_$__,__firefox__,__ksabCssCount,__opera,__sogou_secure_input,_double11_,chrome,chrome.app.InstallState,chrome.csi,console,defaultStatus,document.body.onmouseenter,document.body.onpage,document.body.style.backgroundBlendMode,document.body.style.lineBreak,document.body.style.minWidth,document.body.style.msTextSizeAdjust,document.body.style.textAlignLast,document.body.x-ms-acceleratorkey,document.defaultCharset,document.documentElement.onresize,document.fileCreatedDate,document.msCapsLockWarningOff,document.onmousemove,document.onselectionchange,document.scrollingElement.style.fontVariantNumeric,document.selection,document.selection.typeDetail,external,external.AddFavorite,external.IsSearchProviderInstalled,flyflow_wallpaper_js,getMatchedCSSRules,greentea,isNodeWhitespace,jesion,onerror,onmessage,onoperadetachedviewchange,password_manager_enabled,performance,showModalDialog,taobrowser_Event,weatherBridge,webkitAudioContext.prototype.close,webkitRequestFileSystem",
        "visibility",
        "bindBuffer",
        "lbh8gxwxci|tah",
        "5",
        "ARRAY_BUFFER",
        "DispatchEvent",
        "getExtension",
        "mimeTypes",
        "$_fb",
        "onicecandidate",
        "useProgram",
        "HTMLObjectElement",
        "offsetLeft",
        "o__vyduvaj__R_vyduvaj_Duqtud?atu",
        "#f82",
        "opener",
        "document-fragment",
        "Msxml2.XMLHTTP.3.0",
        "blnyGhccdm",
        "T",
        "HIGH_INT",
        "double",
        "content",
        "d LMO,",
        "wixxtqki|qwvMbK{pwksai~mKnti{p",
        "TEMPORARY",
        "var cur_ele = this;",
        "native",
        "public",
        "attachEvent",
        "i^\\$SwYr]zy_",
        "mozItems",
        "chargingTime",
        "statusText",
        "parentElement",
        "stringify",
        "offsetHeight",
        "setItem",
        "Storage",
        "chrome",
        "executeSql",
        "Msxml2.ServerXMLHTTP.5.0",
        "createOffer",
        "hash",
        "[object Array]",
        "fillStyle",
        "wamjlzq~mz",
        "vertexPosArray",
        "iframe",
        "length",
        "parse",
        "b",
        "<!--",
        "write",
        "options",
        "package",
        "touchend",
        "var submit=function(){for(var t=cur_ele;t!==document&&(!t.tagName||\"form\"!==t.tagName.toLowerCase());)t=t.parentElement;t!==document&&t.submit()};",
        "stopPropagation",
        "y)tjxuoj P\\JCLIO]JG D/<d;5d;+0EI",
        "performance",
        "radio",
        "HTMLFormElement",
        "null",
        "//",
        "assign",
        "HTMLEmbedElement",
        "clientY",
        "setServerData",
        "source",
        "$bmF0aXZlRmlVyUHJ",
        "data",
        "PerformanceObserverEntryList",
        "vdFm",
        "{\"optional\" : [ {\"RtpDataChannels\" : true} ]}",
        "cookieEnabled",
        "LOW_FLOAT",
        "ntr}}Cyragb~S_cyragb~",
        "FSSBB",
        "forEach",
        "outerHTML",
        "$_nd",
        "item",
        "characterSet",
        "createProgram",
        "scroll",
        "TRIANGLE_STRIP",
        "runtime",
        "abort",
        "^(\\[object) Location|Object|DOMPrototype]",
        "onloadstart",
        "vf\\|I\\Fwj}ran lxmn\\]\\|Ih",
        "checkbox",
        "CREATE TABLE IF NOT EXISTS EkcP_t (id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, value TEXT NOT NULL, UNIQUE (name))",
        "vertexPosAttrib",
        "ownerElement",
        "Response-Type",
        "fontList",
        "clear",
        "Count",
        "onabort",
        "a=candidate:",
        "experimental-webgl",
        "time",
        "getItem",
        "meta",
        "touchmove",
        "wlwtxpqvJlwtxpqvqvnwJlwtxpqvum|i",
        "detachEvent",
        "cellular",
        "'null' is not an object",
        "precision",
        "setTimeout",
        "dPT@qi+PT@qi",
        "frames",
        "charset",
        "; path=/",
        "mediaDevices",
        "enum",
        "^(?:\\d{1,3}(?:\\.|$)){4}",
        "eMqe}gPeia*Mqe}gPeia",
        "timeout",
        "charAt",
        "captureStackTrace",
        "unicode",
        "filename",
        "GetNextReqID",
        "enumerateDevices",
        "r#!#c #rrrErfcic9cbc%c&o;o|ExE3EQx?x{tqtktitAtVtvtNhPh9W[Jmi^i{HIHjH/A~prpopxpg1E1BsgVDVEV8V4YqY K9K%R{FBF.F|M3MQMPMNMaM^M*M>M{M]QOQ2Q)Q.Q|wswYwMw%w*8l8D8U8I8f8O828_8Z8@8*8=I5I^I<GEGtGAGYGRGdG!fWfpfYfUfRfQfBfSfTf~PuP_PZP5P~P]P OEOtOi9r9E9t9W9i999b9B9S9T2L2B2S2u2T2=2>bkb%b)b?vovhvPv9v7vSv6LRL(L NmN{N]N jmjojxjsjKjbjj->-}-]7G7Z7dXcX7X;X|BkBDBUBRB8BjB)aYaGa+a/S/S]n~n&u5u^000C0y0Z0@0&0)0<TMTwTGTOT$T^T(T=T:T[T CcCAC1C+C<C?C;64gEgUgLyOya~7~B~C~!!r!o!:@i@F@Q@I@X@d@.$D$Y$f$O$2$T%H^O&f&j&;*:(V(()W)H)s)I)(+o+J+&=k>~.Y.v.z?W?N/a/{:9:b:S:}{2[n]F#r]#rq9rqvrq7rqBrq}rq|rrkrrDrrJrrYrrurrCrcprcsrcRrcIrcfrcOrcNrczrcarcurcgrcerc)rc?rc:rc{rkqrl4rldrDkrDWrD1rDKrDOrDbrDLrDnrDTrDgrD5rD@r2nrborbxrb6rbyrb(rb+rb]rvqrLhrLvrL<rL|rNurN.rjhrjYrjMrjwrjOrj2rj-rjzrjurjTrj4rjerj$rj^rj=rj>rj{rS6rS4rS*rn$rn+rn<rn.ru.ru/ru{r0qr0Lr07rTarT@rCqrCyrC(mHVmQMmwCmG6mG4mG+mf1mfSmf0mf~mf:mPAmO6mOdmO@m9?mbAmbKmb3mbFmbQmbImbfmb6mb[mvBmv5mLKmNVmNBmN_mN/m- m7vm7dm7!m7$m7+ElVEoCEoyEEFEEGExaEx|EtlEtpEtYEtwEtbEtLEt0EtCEt_Et%Eh]EWIEA2EAgEp8EpfEp]E1bE1SEs>Es:Es{EYvEY<EKWEKsEK7EKgEU6EU4EU~EU$EU(EU=EU/EU{EU[",
        "height",
        "mouseover",
        "Z8XHJJY.bmF0aXZlRmlVyUHJ()",
        "select-",
        "boolean",
        "export",
        "host",
        "none",
        "createShader",
        "exec",
        "^\\s+|\\s+$",
        "parseFromString",
        "touchstart",
        "goto",
        "([0-9]{1,3}(\\.[0-9]{1,3}){3}| (([0-9a-f]{1,4}:){7,7}[0-9a-f]{1,4}|([0-9a-f]{1,4}:){1,7}:|([0-9a-f]{1,4}:){1,6}:[0-9a-f]{1,4}|([0-9a-f]{1,4}:){1,5}(:[0-9a-f]{1,4}){1,2}|([0-9a-f]{1,4}:){1,4}(:[0-9a-f]{1,4}){1,3}|([0-9a-f]{1,4}:){1,3}(:[0-9a-f]{1,4}){1,4}|([0-9a-f]{1,4}:){1,2}(:[0-9a-f]{1,4}){1,5}|[0-9a-f]{1,4}:((:[0-9a-f]{1,4}){1,6})|:((:[0-9a-f]{1,4}){1,7}|:)|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-f]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])) )",
        "disabled",
        "onautocomplete",
        "443",
        "$_fr",
        "returnValue",
        "Msxml2.ServerXMLHTTP.6.0",
        "try{return __filename;}catch(e){}",
        "timeZone",
        "withCredentials",
        "mouseup",
        "osqbfsxqDuvduexRsqbfsxq_duvduexRsxus{>awy~Rtusdkbf5q||rqs{",
        "DOMParser",
        "enableVertexAttribArray",
        "rR#r:ckcEE9Ebx[x]tWt1HP171zs_s+s=s{s}VhVQKhK.K?K}FuF&MiMHM7MzM?QrQ1QGQfQ0QTQ{Q}www8wGwfwOw9w)8%8^8?IxIRIFI(I)G1GsGwGZGeG:ftfGfffOf2fbfjf-f|O1OzOXOTOC9y2r2k2lbobjb-vXL+L=N~N!N$N&N*N)N<jhjJjAjpj3jRjOj7j@j$-JX!BtBiBHB6a<0%T{%u%g&}?6?g#2#rrHrrprrsrcMrlQrljrm}rDqrDirDwrDIrDfrD*roOro9rNer-=rShrSWrS!rS@rZuczXcXGmiamG[mG]m9;m9{mS@D]UEtMEtZEt5EtdEt!Et@",
        "char",
        "QQBrowser",
        "CallSite",
        "instanceof",
        "safari",
        "getRandomValues",
        "$_cDro",
        "c#r*^p#H#rklrkmrkDrkorkErkxrktrkhrkWrkJrkirkHrkurltrSD",
        "contextmenu",
        "$b_onNativeResponse",
        "FRAGMENT_SHADER",
        "Msxml2.XMLHTTP.5.0",
        "FileReader",
        ">>>=",
        "text/javascript",
        "offsetX",
        "v>xpx~",
        "wifi",
        "Gamepad",
        "(evaluating 'null[0]')",
        "globalStorage",
        "escape",
        "fonts",
        "uniform2f",
        "[null] is not an object",
        "tests",
        "Unterminated multiline comment",
        "k__myvxh}lyh_iwh}fj_zd",
        "lhxaxc|jb",
        "lbh=|wwxc",
        "catch",
        "internal",
        "Uint8Array",
        "transient",
        "Msxml3.XMLHTTP",
        "SEND",
        "qrsfwqs{}dw}|",
        "screenX",
        "webkitPersistentStorage",
        "webkitRequestFileSystem",
        "}_7gngpkwo_-()_6geqtfgtD_ugngpkwoDecnn7gngpkwo",
        "openDatabase",
        "with",
        "return new a(",
        "$_vvCI",
        "toFixed",
        "http-equiv",
        "Intl",
        "cPc}jNj}wcp",
        "TK_NUMBER",
        "password",
        "external",
        "RTCPeerConnection",
        "var getAttribute=function(name){return cur_ele.getAttribute(name);};",
        "LOW_INT",
        "split",
        "long",
        "cancelBubble",
        "AnalyserNode",
        "mkwt}{hj{g{t{~{hmuzsbyw",
        "HIGH_FLOAT",
        "onupgradeneeded",
        "nodeValue",
        "srcElement",
        "$b_fetchQueue",
        "uniformOffset",
        "nuviztvbezvagrgzba",
        "|__fu<heE__j(u<he",
        "isNaN",
        "enctype",
        "interface",
        "deviceId",
        "onbeforeunload",
        "bVdaWLKnfLrf_TMHPTD_",
        "include",
        "contains",
        "origin",
        "parent",
        "^((?:[\\da-f]{1,4}(?::|)){0,8})(::)?((?:[\\da-f]{1,4}(?::|)){0,8})$",
        "bluetooth",
        "Msxml2.ServerXMLHTTP",
        "video",
        "decodeURIComponent",
        "attribute vec2 attrVertex;varying vec2 varyinTexCoordinate;uniform vec2 uniformOffset;void main(){varyinTexCoordinate=attrVertex+uniformOffset;gl_Position=vec4(attrVertex,0,1);}",
        "private",
        "shenjian",
        "insertBefore",
        "acos",
        "toUpperCase",
        "JSON",
        "f<b>jiomjg)<b>jiomjg",
        "/:user_fonts",
        "shift",
        "acceleration",
        "alert",
        "Float32Array",
        "linkProgram",
        "substring",
        "protected",
        "HTMLElement",
        "transferChannel",
        "arity",
        "nEvr}IzuvbUEvr}IzuvbOg~P 4tgzivK 6bageb} OZYTszgP",
        "$b_platform",
        "AddSearchProvider",
        "parseInt",
        "referrer",
        "INSERT OR REPLACE INTO EkcP_t (name, value) VALUES(?, ?)",
        "return",
        "objectStore",
        "HTMLGenericElement",
        "QTP_EPE_HOOK",
        "DateTimeFormat",
        "datas-ts",
        "<",
        "substr",
        "volatile",
        "(^\\s*)|(\\s*$)",
        "1.234",
        "send",
        "url(#default#userdata)",
        "static",
        " host ",
        "setLocalDescription",
        "prop",
        "nextSibling",
        "layerY",
        "setTime",
        "javascript:",
        "1",
        "r[#Egx.W|JcArAzpvpS1x1Qs4s!s%s)s?s;VZV]KqKtK^K>UUUFUQU9UbULUjUXR?R:F0FCF6F5FdF@F*F=QcQlQmQEwNw-wCwg8/8;8{8|GfG9f>f?f:f{PBPSOsOYOKOROMOwOIOP9Z9~bEbtbhbibAb1bVbKv~v@v$v^v)v/L<L;NDNJjFjIjXju727n707g7%7=7>zUXBXnX0XyBoBxBhBJBABKBFBwBaBTB$B^@G@P@~@@%s%R%F%f%2%B^i^A(3(F(M(8(f(O(-(a(S(u)?+D=D=E=^===;<q<r<D<o<A>4>5.3.Q.I.O.>.[?-?X/}:c:k:t;.;/;;{m{o{J[u]q]U]R#P#rmPrmXrm6rm@rLKrL3rj[r-MrSarSTmLUmLbmL$mL}mNamN6mN:mjcmjSmjum-im-pm-Ym-3m7Lm7zmz mXrE1CE1^E1]EskEsjEs7",
        "^href|pathname|search|host|hostname|port|hash|protocol$",
        "layerX",
        "getBattery",
        "offsetWidth",
        "rangeMax",
        "isFinite",
        "toGMTString",
        "rows",
        "constructor",
        "[\\\\\\\"\\u0000-\\u001f\\u007f-\\u009f\\u00ad\\u0600-\\u0604\\u070f\\u17b4\\u17b5\\u200c-\\u200f\\u2028-\\u202f\\u2060-\\u206f\\ufeff\\ufff0-\\uffff]",
        "parseFloat",
        "___ts___",
        "~np{wjtjcjmjuzdibohf",
        "STATIC_DRAW",
        "beta",
        "Mouse",
        "firstChild",
        "error",
        "~tfmfojvnDfwbmvbuf",
        "t@vf{pO1papnatzy",
        "$_f0",
        "trim",
        "else",
        "orientation",
        "http://",
        "<!--[if gt IE ",
        "__onload__",
        "snmpn{g",
        "GetOriginalUrl",
        "i>wn{AygfBwnwAfl{j|wy{Xb{kagf",
        "{6*,H6hj)xvp",
        "qrbwfsb",
        "enik}t*Na{hLh{uan C. ?kjpnkh*-",
        "transaction",
        "connection",
        "getAllResponseHeaders",
        "crypto",
        "use strict",
        "Name expected",
        "}Yetq4(*F4(*",
        "audio",
        "webkitIndexedDB",
        "j;=G}zcmzk~xv2K~wzkve Dvx}~ez Le~2:ffcavqq2Mziyvev2?zcmzk~xv Ezlz CK Gif *, K}~e2kv}fdv2C> Jdvik_? kzjk Iz|lcvi2;@EGifXc~|}k2?zcmzk~xv CK +* C~|}k <okzeyzy2?zcmzD_@ey~v2J<:IfwfkfC~|}k 9fcy2FI Df}vekp Le~xfyz Iz|lcvi2;if~y Jvej K}v~2Bveevyv Jve|vd DE2;;: Lx}ze2xcfxb)[(-_m(Y(2Jvdjle|BveevyvIz|lcvi2D@ C8EK@E> 9fcy2Jvdjle|JvejEld*C C~|}k2mziyvev2?zcmzk~xvEzlzK}~e2J<:=vccwvxb2Jvdjle|<dfa~2Kzcl|l Jve|vd DE2:viif~j >fk}~x J:2=cpdz C~|}k Ifwfkf C~|}k2JfD8X;~|~k C~|}k2JfD: Jvej Iz|lcvi2?PO~PlveA2jjk2jvdjle|XjvejXeld+K2|d_dze|dze|2Cf}~k Bveevyv2k~dzj ezn ifdve2jvdjle|XjvejXeld+C2jzi~{Xdfefjgvxz2Jvdjle|JvejEldX*K K}~e2:fcfiFJL@XOK}~e2;if~y Evjb} J}~{k 8ck2Jvdjle|Kzcl|lIz|lcvi29ze|vc~ FKJ2D@ CveK~e|_>9 Flkj~yz PJ2=QD~vfNl_>9(/[*[2}zcmzXezlzXiz|lcvi2JJK Dzy~ld2:fli~zi Ezn2B}dzi Dfeylcb~i~ 9fcy2?zcmzk~xv CK )* Lckiv C~|}k <okzeyzy2?zcmzk~xv CK ), Lckiv C~|}k2Ifwfkf Dzy~ld2;if~y Jvej 9fcy2|flyp2jvejXjzi~{XxfeyzejzyXc~|}k2J=~eyzi2efkfXjvejXxabXdzy~ld2d~l~2DIfxbp GI: 9fcy28eyif~y:cfxb Iz|lcvi2Jvdjle|JvejEldX+C C~|}k2jvejXjzi~{Xk}~e28vGve|Pvzi2xvjlvc29E Df}vekpFK 9fcy2oXjjk2EfkfJvejDpvedviQvn|p~2?zcmzk~xv CK ** K}~e <okzeyzy28j}czpJxi~gkDK 8ck2Efkf Jvej ;zmvev|vi~ L@2Ifwfkf :feyzejzy 9fcy2Ifwfkf Dzy~ld @kvc~x2d~l~zo2Efkf Jvej >lidlb}~ L@2JJK M~zkevdzjz C~|}k2C>_Fi~pv2}pxf{{zz2oXjjkXlckivc~|}k2;=?z~8N.X82=QQNO9KFK_Le~xfyz2;zmvev|vi~ Jve|vd DE 9fcy2jvejXjzi~{Xdfefjgvxz2Gvyvlb 9ffb 9fcy2C>X=QP~e|9~Bv~J}lXJ(,XM)Y)2C>X=QP~e|9~Bv~J}lXJ(,XM)Y*2?zcmzk~xvEzlzCK Gif *, K}2D~xifjf{k ?~dvcvpv2Jvdjle|Jvej=vccwvxb2JJK Dzy~ld @kvc~x28eyif~y<dfa~2Jvdjle|JvejEldX*I2@K: Jkfez Jzi~{2jvejXjzi~{Xjdvccxvgj2oXjjkXdzy~ld2C>_J~e}vczjz2Ifwfkf K}~e @kvc~x2xzeklipX|fk}~x2:cfxbfg~v2Cld~eflj_Jvej2=cfi~y~ve Jxi~gk 8ck2Efkf Jvej >lidlb}~ 9fcy2CK?PJQB 9fcy2>J_K}v~2Jvdjle|EzfEld_*K_)28ivw~x2}vejXjvejXefidvc2Cf}~k Kzcl|l2?PH~?z~X,[J C~|}k2C~eyjzp {fi Jvdjle|28I :ipjkvc}z~ ;92Jvdjle| Jvej Dzy~ld2jvdjle|XjvejXeld+,2}vejXjvejXwfcy2Cld~eflj_Jxi~gk2JJK :feyzejzy2Jvdjle|;zmvev|vi~Iz|lcvi28eavc Dvcvpvcvd DE2Jvdjle|K}v~SkzjkT2=QCveK~e|?z~XDX>9(/[*[2?zwizn FKJ2>J+,_8ivwS8eyif~yFJT2Jvdjle| Jvej C~|}k2:}fxf xffbp2}zcmzXezlzXk}~e2GE Df}vekpFK Dzy~ld2C>X=QBvKfe|XD(0XM)Y+2;if~y Jzi~{2Jvdjle|J~e}vcvIz|lcvi2}zcmzk~xv2C>X=QBvKfe|XD(0XM)Y)2Efkf Jvej ;zmvev|vi~ L@ 9fcy2JJK C~|}k2;=G<dfa~2nzvk}zi{fekezn Iz|lcvi2IfwfkfEld*I2;@EGifXdzy~ld2Jvdjle| Jvej Eld,,2JJK ?zvmp @kvc~x2C>cfxb+ Iz|lcvi_[/[,2>zfi|~v2efkfXjvejXxab2Kzcl|l Jve|vd DE 9fcy2D@L@ <O Efidvc2?PH~?z~X.,J 9fcy2EfkfJvejDpvedviQvn|p~ 9fcy2plefjgifXwcvxb2}zcmzXezlzXefidvc2Cld~eflj_Jzi~{2KD Df}vekpFK Efidvc2Jvdjle|JvejEldX*Cm C~|}k2Jvdjle| Jvej Eld+,2Jdvik>fk}~x Dzy~ld2|zfi|~v2xvjlvcX{fekXkpgz2Jvdjle| Jvej 9fcy2jdvccXxvg~kvcj2D=~evexz GI: 9fcy2=QCveK~e|?z~_>9(/[*[2Jvdjle|8idze~ve2Ifwfkf 9fcy2xzeklipX|fk}~xXwfcy2oXjjkX}zvmp2JJK C~|}k @kvc~x2K}viCfe2oXjjkXc~|}k2;~ewfc Iz|lcvi2Jvdjle|9ze|vc~Iz|lcvi2BE Df}vekpFKJdvcc Dzy~ld2}pgliz2Jvdjle|Kvd~cIz|lcvi2Dvcvpvcvd Jve|vd DE2Efkf Jvej Bveevyv L@2}zcmzXezlz2?zcmzk~xv CK ,, Ifdve2Efkf Jvej Bveevyv 9fcy2Jvegpv2Jvdjle|Gleavw~Iz|lcvi2jvdjle|XjvejXeld+Cm2C>_Bveevyv2Jvdjle| Jvej Iz|lcvi2Qvn|p~XFez2;if~y Jzi~{ 9fcy @kvc~x2=QB8KAN2xfli~zi ezn2Jvdjle|<dfa~Iz|lcvi2D@L@ <O 9fcy28eyif~y <dfa~2Efkf Evjb} 8ivw~x L@2C:; :fd2=lkliv Dzy~ld 9K2M~mfXzokivxk29ve|cv Jve|vd DE 9fcy2}vejXjvejXiz|lcvi2JEldX*I2JEldX*K2}vejXjvej2JJK Lckiv C~|}k2Ifwfkf Iz|lcvi2Ifwfkf C~|}k2?veldve2eznc||fk}~x2;=?z~8N,X82}vejXjvejXc~|}k2Gcvkz >fk}~x2JEldX*C2?zcmzk~xv CK +, C~|}k2Dpvedvi Jve|vd Qvn|p~ 9fcy2c|XjvejXjzi~{Xc~|}k2D@L@ <O C~|}k2Ifwfkf K}~e2JfD8 9fcy2Gvyvlb2Jvdjle| Jvej2Jgvx~flj_Jdvcc:vg2jvejXjzi~{2;M Df}vekpFK Dzy~ld2Jkvwcz_Jcvg2dfevxf2=cpdzXC~|}k2{qqpjXyfjgp2JxizzeJvej2xcfxb)[(-2Ifwfkf :feyzejzy 9fcy @kvc~x28i~vc2BE Df}vekp Dzy~ld2DfkfpvCDvil N* dfef2?veyjzk :feyzejzy2Ifwfkf @kvc~x2?K: ?vey2JJK Lckiv C~|}k @kvc~x2JJK M~zkevdzjz Ifdve2Efkf Evjb} 8ivw~x L@ 9fcy2x}e{qo}Xdzy~ld2JEld:feyX*K2xzeklipX|fk}~xXiz|lcvi2yz{vlck_ifwfkfXc~|}k2Efkf Jvej Dpvedvi2Dpvedvi Jve|vd DE28ggcz :fcfi <dfa~2nzvk}zi{fekIz|2Jvdjle|DvcvpvcvdIz|lcvi2vi~vc2;if~y Jzi~{ 9fcy2:Gf* GI: 9fcy2D@ C8EK@E>2Jvdjle|BfizveXIz|lcvi2kzjk+, Iz|lcvi2jg~i~k_k~dz2;zmvev|vi~ Jve|vd DE2JxizzeJzi~{2Ifwfkf2xlij~mzX{fekXkpgz2JK?z~k~_m~mf2x}e{qo}2Jvdjle| :cfxb=fek *82Ifwfkf :feyzejzy Iz|lcvi2jvdjle|XezfXeld*I2>A Df}vekpFK Dzy~ld2:}lc}f Ezlz Cfxb2ifwfkfXeld*C2}zcmzXezlzXlckivC~|}kzokzeyzy2Jvdjle|Fi~pvIz|lcvi2Jvdjle|JvejEldX+Cm C~|}k2DP~e|?z~_(/[*[_:)X9fcy2;=GJ}vfEmN,X>92Ifwfkf 9cvxb2}zcmzXezlzXlckivc~|}k2|d_o~}z~2C>cfxb+ C~|}k_[/[,2>lavivk~ Jve|vd DE2Dvcvpvcvd Jve|vd DE 9fcy2ifwfkfXeld*I2JKO~}z~_m~mf2=QQ}lePlve_>9(/[*[2efkfXjvejXxabXc~|}k2xfcfifj2Efkf Jvej >lidlb}~2Efkf Jvej Jpdwfcj2Ifwfkf C~|}k @kvc~x2Cf}~k Kvd~c2xlij~mz2yz{vlck_ifwfkf29}vj}~kv:fdgczoJvej 9fcy2C>_Eldwzi_Ifwfkf K}~e2dfefjgvxzyXn~k}flkXjzi~{j2?zcmzk~xv CK *, K}~e2jvdjle|XjvejXeld*CM2;@EGif2Afdfc}vi~2jvejXjzi~{Xc~|}k2}zcmzXezlzXwcvxb2Cf}~k 9ze|vc~2Dpvedvi Jve|vd Qvn|p~2;if~y Jzi~{ @kvc~x2Ifwfkf 9fcy @kvc~x2Eveld>fk}~x2Jfep Dfw~cz L; >fk}~x Iz|lcvi2>zfi|~v 9fcy @kvc~x2jvdjle|XjvejXeld*Cm2plefjXk}~e2jvdjle|XezfXeld*KXxfey2Efkf Jvej Dpvedvi L@ 9fcy2c|jzi~{2=QPfl?z~XIX>9(/[*[2Cf}~k Gleavw~2wvjbzim~ccz2jvdjle|XjvejXeld+Km2jvdjle|XjvejXk}~e2C> <dfa~28eavc~EznC~g~2Jvdjle|JvejEldX+K K}~e2Jvdjle|BfizveX9fcy2d~l~zoXc~|}k2Efkf Jvej Bveevyv2Ifwfkf Efidvc @kvc~x2>zfi|~v @kvc~x2jvejXjzi~{Xdzy~ld2Jdvik Qvn|p~2Ifwfkf :feyzejzy @kvc~x2Efkf Jvej Bveevyv L@ 9fcy2;=G Jx Jvej ?zlz*[_([*2C>_Eldwzi_Ifwfkf 9fcy2Gvyvlb 9ffb2oXjjkXxfeyzejzy2Jlej}~ezXLx}ze2Ifwfkf 9cvxb @kvc~x2I~e|f :fcfi <dfa~2;zmvev|vi~ FKJ2Jdvik Qvn|p~ Gif2=QCveK~e|?z~XDX>9B28eyif~y:cfxbXCvi|z Iz|lcvi2gifgfik~fevccpXjgvxzyXn~k}flkXjzi~{j2:lk~mz Dfef2k~dzj2C> Jdvik_? kzjk 9fcy2;@EGifXC~|}k2jvejXjzi~{Xwcvxb2Cf}~k ;zmvev|vi~2gifgfik~fevccpXjgvxzyXn~k}Xjzi~{j2jvdjle|XjvejXeld*C2DPfle| GI: Dzy~ld2;=>fk}~xGN,X9@>,?BXJFEP2}vejXjvejXdzy~ld2JJK ?zvmp2C>X=QQ}lePlveXD[)XM)Y)2DpvedviLEzn Iz|lcvi2Efkf Evjb} 8ivw~x 9fcy2Jvdjle|>lavivk}~Iz|lcvi2{vekvjp2}zcmzXezlzXc~|}k2?zcmzk~xv Ezlz FKJ 9fcy2efkfXjvejXxabXwfcy2jvdjle|XjvejXeld*I2C~eyjzp Jvdjle|2jvdjle|XjvejXeld*K2JxizzeJzi~{Dfef2<Kildg Dpvedvi_QN2}zcmzXezlzXk}~ezokzeyzy2Efkf Evjb} 8ivw~x2C>_>lavivk~2Jdvik_Dfefjgvxzy2Kvd~c Jve|vd DE2C> <dfa~ Efe8D<2Ifwfkf :feyzejzy C~|}k @kvc~x2|d_a~e|bv~2=QCveK~e|Bve?z~_>9(/[*[2c|kivmzc2gvcvk~ef2>zfi|~v 9fcy2;if~y Jvej2C>_Gleavw~2Jdvik>fk}~x 9fcy2Jvdjle| Jvej K}~e2JJK :feyzejzy 9fcy2:fd~xj_Eviifn2xfli~zi2Fi~pv Jve|vd DE2}zcmzXezlzXc~|}kzokzeyzy2=QCveK~e|?z~XIX>9(/[*[28I :ipjkvc}z~?BJ:J ;92jzi~{2IKNJPlzIfly>f>[m(XIz|lcvi2D~vfNl_gizm2=QP(B2C>_Eldwzi_Ifwfkf Iz|lcvi28eyif~y:cfxb2JfD8 Iz|lcvi2?PH~?z~X+[J C~|}ko2c|XjvejXjzi~{2;vex~e| Jxi~gk 9fcy2yz{vlck2jzxXifwfkfXc~|}k2:fcfiFJL@XIz|lcvi2kzjk Iz|lcvi2Kvd~c Jve|vd DE 9fcy2=QP~e|9~O~e|J}lXJ(-2IfwfkfEld*C C~|}k2dfefjgvxzyXn~k}Xjzi~{j2jvdjle|XjvejXeld*,2:ffc avqq2Jvdjle|EzfEldX*C2JKO~e|bv~2JxizzeJvejDfef2;=GNvNvN,X>92Jvdjle|JvejEldX*C C~|}k29ve|cv Jve|vd DE2>lidlb}~ Jve|vd DE2J<:IfwfkfC~|}k2}p{feoiv~e2DP~e|?z~>9(/[*[:X9fcy2jvdjle|XjvejXc~|}k2?zcmzk~xv CK -, Dzy~ld2;if~y Jvej =vccwvxb2Ifwfkf Kzjk( 9fcy2Efkf Jvej Dpvedvi 9fcy2jvejXjzi~{XxfeyzejzyXxljkfd2Jvdjle|EzfEldX*K2Jvdjle| Jvej Eld*,2dfefjgvxz2KC Df}vekp Dzy~ld2}zcmzXezlzXdzy~ld2CK?PJQB2Ifwfkf :feyzejzy xljkfdz 9fcy2Dpvedvi*2;if~y Jvej ;zmvev|vi~2J}vfEm_gizm2jvdjle|XezfXeld*C2=QCveK~e|?z~X<CX>9B2plefj2jvdjle|XezfXeld*K2K~dzj Ezn Ifdve2}zcmzXezlzXwfcy2efkfXjvejXxabXiz|lcvi2Efkf Jvej >lidlb}~ L@ 9fcy2;@EGifXwcvxb2=QCveK~e|?z~X<CX>9(/[*[2JJK M~zkevdzjz Dzy~ld2Ifwfkf :feyzejzy C~|}k2JJK M~zkevdzjz 9fcy28I ;AXBB2;if~y Jvej J<D:2Efkf Jvej Dpvedvi L@2:fd~e| Jffe2DPlggp GI: Dzy~ld2Ifjzdvip2Cf}~k >lavivk~2Ifwfkf :feyzejzy xljkfd 9fcy2=QCveK~e|?z~JXIX>92?zcmzk~xv Ezlz FKJ2Bv~k~_gizm2IfwfkfX9~|:cfxb2=QP9BJAN2?veyjzk :feyzejzy 9fcy2Jvdjle|>zfi|~ve2;vex~e| Jxi~gk2jvejXjzi~{Xxfeyzejzy2}vejXjvejXk}~e2Jvdjle|JvejEldX+Km K}~e2Cf}~k Fy~v29}vj}~kv:fdgczoJvej",
        "cygJ+",
        "getAttribLocation",
        "PointerEvent",
        "0000",
        "$_fpn1",
        "; expires=",
        "lineno",
        "touches",
        "reset",
        "(near '... null[0]...')",
        "readwrite",
        "children",
        "gQGJfys}l(I=R",
        "break",
        "extends",
        "addBehavior",
        "y;nuiq}g|k.rgynJ;nuiq}g|k.rgyn",
        "description",
        "bGd~ckdrrBgqnld",
        "k$FhyK98hemiyh9buii}wVK98hemiyhCyiiu{y9ydjyh",
        "_",
        "~snpdyE5fbm3mbzfs *I Zpouspm",
        "l$",
        "byte",
        "typeof",
        "complete",
        "localDescription",
        "close",
        "qrcklmDoExthWJiHAp1sVYKU3RFMQw8IGfPO92bvLNj.7zXBaSnu0TC6gy_4Ze5d{}|~ !#$%()*+,-;=?@[]^",
        "[;&]",
        "text/html",
        "fillRect",
        "﻿",
        "$_f1",
        "{             \"iceServers\" : [                 {\"url\" : \"stun:stun01.sipphone.com\"}, {\"url\" : \"stun:stun.ekiga.net\"},                 {\"url\" : \"stun:stun.fwdnet.net\"}, {\"url\" : \"stun:stun.ideasip.com\"},                 {\"url\" : \"stun:stun.iptel.org\"}, {\"url\" : \"stun:stun.rixtelecom.se\"},                 {\"url\" : \"stun:stun.schlund.de\"}, {\"url\" : \"stun:stun.l.google.com:19302\"},                 {\"url\" : \"stun:stun1.l.google.com:19302\"}, {\"url\" : \"stun:stun2.l.google.com:19302\"},                 {\"url\" : \"stun:stun3.l.google.com:19302\"}, {\"url\" : \"stun:stun4.l.google.com:19302\"}             ]         }",
        ":\\d+",
        "b__cqhudq_du~kt~sd+__vdacqhudq_du~kt~sd+__rdkdmhtl_du~kt~sd+__ewcqhudq_du~kt~sd+__cqhudq_tmvq~oodc+__vdacqhudq_tmvq~oodc+__rdkdmhtl_tmvq~oodc+__ewcqhudq_tmvq~oodc+__vdacqhudq_rbqhos_etmb+__vdacqhudq_rbqhos_em",
        "gGit;jj}ylyh{}",
        "webstore",
        "Msxml.XMLHTTP",
        "<EMBED id=",
        "bgsound",
        "sessionStorage",
        "encoding",
        "responseXML",
        "3jeALeSsa6",
        "SELECT value FROM EkcP_t WHERE name=?",
        "execScript",
        "<meta\\s+http-equiv=[\"']?refresh[\"']?\\s",
        "Unexpected token: ",
        "gmjc_biie}|Zgit;hcgyncihMnylnNcg}ZgitCh|}r}|><ZgitL}ko}mn;hcgyncih@lyg}",
        "short",
        "enable_",
        "dispatchEvent",
        "final",
        "callback",
        "dumpAll",
        "*",
        "GetResponseHeader",
        "random",
        "$b_callHandler",
        "throw",
        "try{return (window instanceof Window);}catch(e){}",
        "mousemove",
        "save",
        "\u0000",
        "objectStoreNames",
        "Submit",
        "offsetUniform",
        "display",
        "Entity",
        "$_JQnh",
        "80",
        "selected",
        "appVersion",
        "multipart/form-data",
        "windows-1252",
        "Missing catch/finally blocks",
        "frame",
        "0",
        "<div>IE8</div>",
        "abstract",
        "_ts_",
        "toDataURL",
        "=true",
        "finally",
        "removeAttribute",
        "textarea",
        "VERTEX_SHADER",
        "msIndexedDB",
        "precision mediump float;varying vec2 varyinTexCoordinate;void main() {gl_FragColor=vec4(varyinTexCoordinate,0,1);}",
        "area",
        "replaceState",
        "Msxml2.XMLHTTP.4.0",
        "ethernet",
        "Decrypt Ajax Response Failed - ",
        "\\r\\n?|[\\u2028\\u2029]",
        "bb82kj",
        "; Secure",
        "bufferData",
        "offsetY",
        "Msxml2.ServerXMLHTTP.3.0",
        "keyup",
        "attrVertex",
        "FSSBA",
        "screenY",
        "attachShader",
        "Unexpected token ",
        "wZwjrmk| ql[\"jjVPsr\" kti{{ql[\"kt{qlXQNSNnVOWKWVjSKOOknKjjVPKNNiiNNjlkmNj\" aql|p[\"Nxb\" pmqop|[\"Nxb\"(ZMwjrmk|(",
        "11.678",
        "accelerationIncludingGravity",
        "n__DGC__;BB>_ABG<9<8E",
        "getElementsByTagName",
        "Please enable cookie in your browser before you continue.",
        "debugger",
        "anchor",
        "createObjectStore",
        "ppaaDrp}4{xrzQpaaDrp}7~rfd@feQpaaDrp}<tj5~h}QpaaDrp}<tjFa",
        "pushState",
        "onprogress",
        "~xfclju+jeefo",
        "Call",
        "qrcklmDoExthWJiHAp1sVYKU3RFMQw8IGfPO92bvLNj-7zXBaSnu0TC6gy_4Ze5d~!@$%^&*()+=<>.?/:;{}[]| ",
        "<span style=\"font-family:mmllii;font-size:114px\">mmmmmmmmmmmlliii</span>",
        "Microsoft.XMLHTTP",
        "toLowerCase",
        "#17e",
        "languages",
        "standalone",
        "android",
        "POST",
        "webgl",
        "</$1",
        "ceil",
        "+",
        "\\b((submit)|(open)|(location)|(cookie)|(onsubmit)|(action)|(href)|(search)|(src)|(setAttribute)|(getAttribute))\\b",
        "|te_eulgjhEteerrnvkhoi",
        "unescape",
        "OPEN",
        "post",
        "$b_setup",
        "kn",
        "textBaseline",
        "wimax",
        "getServerDataInCookie",
        "result",
        "\\b[^>]*>([\\s\\S]*?)<\\/",
        "import",
        "z__ryy*wjfyj-wfrjGryy*zrxytr1:",
        "ownerDocument",
        "self",
        "attributes",
        "mozConnection",
        "webkitRTCPeerConnection",
        "\r\n",
        "mozRTCPeerConnection",
        "o~ufebqd{udR__~eR__~e3bbu~tFujfRuaIur4daieud",
        "getShaderPrecisionFormat",
        "plugins",
        "font",
        "nyc_zuvagzwzve",
        "delete",
        "Msxml2.XMLHTTP.6.0",
        "vlaue",
        "rgba(240,110,53,0.4)",
        "\\r?\\n",
        "Illegal newline after @throw",
        "base",
        "Unenclosed string.",
        "stack",
        "r",
        "serverData",
        "evaluate",
        "unexpected number ending.",
        "setRequestHeader",
        "^(\\[object|function) Location\\b",
        "$_ts",
        "cloneNode",
        "Abort",
        "__anchor__",
        "TK_REG_EX",
        "getParameter",
        "FLOAT",
        "Msxml2.XMLHTTP",
        "continue",
        "removeItem",
        "eioreoe|ehepu}d{jca",
        "capture",
        "_DIV",
        "OverrideMimeType",
        "GetVariable",
        "!",
        "Unenclosed regular expression.",
        "elements",
        "image",
        "true",
        "createBuffer",
        "absolute",
        "void",
        "fromCharCode",
        "jbscheme://",
        "DeviceMotionEvent",
        "y",
        "try{return __dirname;}catch(e){}",
        "\\\\"
    ]
    var o = '_$h9'
    if (path.node.object.type == 'Identifier' && path.node.object.name == o){
        path.replaceWith(t.StringLiteral(s[path.node.property.value]))
    }
}


// 用于在每个 catch() 里面添加一个 console.log 这样可以快速定位哪些 catch 被捕捉到了。
// 一些代码是通过 try catch 来静默获取一些不同环境执行结果以判断环境置办参数的
traverse(ast, {CatchClause: AddCatchLog});

// 用于将某些 s[123] 直接在外部用计算好的内容进行表示，这样会很方便
traverse(ast, {MemberExpression: Replacer});